### ISSUE TITLE
Confusing error message when using empty test classes with JUnit5 runner

### ISSUE THREAD

**Issue by nils-christian** [tapir-test/tapir-extensions#12]
When one uses an empty test class (which might also happen when using feature filtering), the JUnit5 runner throws a confusing exception. Maybe this could be improved?
```
org.junit.platform.commons.util.PreconditionViolationException: No TestIdentifier with unique ID [[engine:tapir]/[TestSuite:testsuite1.TestSuite1]/[TestClass:testsuite1.TestClass1]] has been added to this TestPlan.
	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:297) ~[junit-platform-commons-1.2.0.jar:1.2.0]
	at org.junit.platform.launcher.TestPlan.getTestIdentifier(TestPlan.java:164) ~[junit-platform-launcher-1.2.0.jar:1.2.0]
	at org.junit.platform.launcher.core.ExecutionListenerAdapter.getTestIdentifier(ExecutionListenerAdapter.java:65) ~[junit-platform-launcher-1.2.0.jar:1.2.0]
	at org.junit.platform.launcher.core.ExecutionListenerAdapter.executionStarted(ExecutionListenerAdapter.java:46) ~[junit-platform-launcher-1.2.0.jar:1.2.0]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_121]
	at io.tapirtest.junit5execution.listener.JUnit5ExecutionListener.lambda$notifyStarted$0(JUnit5ExecutionListener.java:111) ~[tapir-extensions-junit5-execution-1.0.2-SNAPSHOT.jar:1.0.2-SNAPSHOT]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_121]
```

**Comment by nils-christian** [comment]
Another confusing error message appears when one tries to execute an empty execution plan (for instance a test suite with negative conditional):
```
WARNUNG: TestEngine with ID 'tapir' failed to discover tests
java.lang.IllegalArgumentException: getDisplayText: Unhandled parameter type: de.bmiag.tapir.execution.model.ExecutionPlan
	at io.tapirtest.junit5execution.descriptor.TestDescriptorBuilder.getDisplayText(TestDescriptorBuilder.xtend:204)
```

**Comment by OLibutzki** [comment]
The first exception occurs, because the execution plan contains a test class which does not have any step. This has to be fixed in the tapir-execution module.

The second exception occurs because of a bug in the JUnit 5 module and is fixed now,
